/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sorter;

import javafx.application.Application;
import javafx.stage.Stage;
import sorter.model.GameEngine;

import static sorter.Constants.*;

public class App extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        GameEngine visualisation = new GameEngine(WINDOW_WIDTH + OPTIONS_OFFSET, WINDOW_HEIGHT);
        visualisation.run();
        primaryStage.setScene(visualisation.getScene());
        primaryStage.setTitle("Sorting Visualisation");
        primaryStage.show();
    }
}